declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_SUPABASE_URL?: string;
    EXPO_PUBLIC_SUPABASE_ANON_KEY?: string;
    EXPO_PUBLIC_AGORA_APP_ID?: string;
    /** EAS project id (generated by `eas init`); required for Expo push tokens. */
    EXPO_PUBLIC_EAS_PROJECT_ID?: string;
    /** Set to 'true' to use real Expo push registration instead of the mock. */
    EXPO_PUBLIC_REAL_PUSH?: string;
    /** Billing / manage-subscription URL opened from payment reminders. */
    EXPO_PUBLIC_BILLING_URL?: string;
    /** Server-side only (Edge Function secret) — never read from client code. */
    DEEPGRAM_API_KEY?: string;
  }
}
